include ../common.mk

all:
	${MAKE} -C fizzbuzz    all
	${MAKE} -C 8cc         all
	${MAKE} -C zlib        all
	${MAKE} -C fizzbuzz-rs all
	${MAKE} -C numguess-rs all

test:
	${MAKE} -C fizzbuzz    test
	${MAKE} -C 8cc         test
	${MAKE} -C zlib        test
	${MAKE} -C fizzbuzz-rs test
	${MAKE} -C numguess-rs test
